### ISSUE TITLE
Marketplace Launch Release TODOs List

### ISSUE THREAD

**Issue by PauliusKu** [BalticAmadeus/OpenedgeAblFormatter#279]
# MLR must haves:
### Quality

- [x] ADE: review failing Whitespace test cases. Fix all major issues @darkeris345 #238 
- [x] #293 @darkeris345 
- [ ] Try Whitespace testing with a few different code bases @darkeris345 
- [x] POSTPONED Introduce Compilation testing @PauliusJaskutelis #74 
- [x] SKIP FOR NOW Introduce Idempotence testing @gustason  #200 
- [ ] No P0 or P1 bugs (tree-sitter and ours) @eglekaz . List those bugs here:
- [ ] ...
### User testing

- [ ] Test on at least 3 different project codebases @eglekaz @PauliusKu @gustason 

### Features

- [x] Expression formatting @gustason #49 
- [ ] Preprocessor directives @eglekaz #217 
- [ ] OnSave formatting settings @PauliusKu #277 
### Settings:

- [x] Create Questionnaire  @eglekaz 
- [x] Review Questionnaire's answers @gustason 
- [x] #306 @gustason 
- [x] Combine some settings @gustason 
- [ ] Review descriptions @gustason 

### Other

- [x] V1 code cleanup @darkeris345 #190 
- [x] #287 @darkeris345 
- [ ] #280 @darkeris345 
- [x] POSTPONED  Write dev guidelines @darkeris345 
- [x] #303

# QA strategy

| **Name**    | **Level**         | **Metric**                                                                              | **Objective**                                             |
|---------------|-------------------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------|
| Telemetry | **Product**  | **Telemetry Data** (e.g., crash reports, latency, settings configuration)                | Stability, performance, real-world usage                   |
| Compilation | **Formatter**| **Number of Compilation Errors After Formatting** divided by the number of code files     | Measure the correctness and reliability of the formatter   |
| Whitespace     | **Formatter**| **Number of Non-Whitespace Changes** in a given code base                                | Measure the correctness and reliability of the formatter   |
| Idempotence | **Formatter**   | **Percentage of source files changed** after 2nd formatting attempt | Formatter idempotence  |
| Parser errors | **Parser**   | **Number of Parser Errors** divided by the number of tree nodes                          | Measure the correctness of the parser                      |
|Functional   | **Function** | **Percentage of Passing Functional Test Cases**                                          | Ensure broad feature support and correct parsing behavior  |

1. Telemetry - TODO
2. Compilation - TODO
3. Whitespace - IN PROGRESS
4. Idempotence - TODO
5. Parser errors - IN PROGRESS
6. Functional - DONE
